name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install

      - name: Lint with Biome
        run: |
          bun run check

      - name: Type check
        run: |
          bun run tsc

      - name: Unit tests
        run: |
          bun test

      - name: Run knowhub
        run: |
          bun run knowhub

      - id: semantic-release
        name: Run semantic-release
        run: |
          bunx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
